import turtle
turtle.bgcolor('black')
turtle.color('white')
def square():
    turtle.color('green')
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.penup()
    turtle.goto(100,100)
    turtle.pendown()
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)


def rectangle():
    turtle.color('pink')
    turtle.penup()
    turtle.goto(-100,-100)
    turtle.pendown()
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(100)
    turtle.penup()
    turtle.goto(100,-100)
    turtle.pendown()
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)

    turtle.exitonclick()


square()
rectangle()
